image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
    - jekyll
    - gollum


build:
    stage: jekyll
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/jekyll jekyll/
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/jekyll

build:
    stage: gollum
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/gollum gollum/
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/gollum
