image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $HUB_USER -p $HUB_PASSWORD

build:
    script:
        - (for each in `find . -maxdepth 1 -mindepth 1 -type d | grep -vw ".git" | sed 's@./@@'`;
          do
            echo "Building $each";
            docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/$each $each/;
            docker push $CI_REGISTRY/$CI_PROJECT_PATH/$each;
            docker tag $CI_REGISTRY/$CI_PROJECT_PATH/$each $HUB_USER/$each;
            docker push $HUB_USER/$each;
          done)

