image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $HUB_USER -p $HUB_PASSWORD 

stages:
    - jekyll
    - gollum


build:
    stage: jekyll
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/jekyll jekyll/
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/jekyll
        - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/jekyll $HUB_USER/jekyll
        - docker push $HUB_USER/jekyll

build:
    stage: gollum
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/gollum gollum/
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/gollum
        - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/gollum $HUB_USER/gollum
        - docker push $HUB_USER/gollum
