image: docker:latest

services:
    - docker:dind

stages:
    - jekyll

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
    stage: jekyll
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/jekyll jekyll/
        - docker push $CI_REGISTRY/$CI_PROJECT_PATH/jekyll
